language: 
  - node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

notifications:
  email:
    - false

sudo:
  - required

install:
  - npm install --unsafe-perm=true --allow-root

script:
  - gulp js

os: 
  - linux

dist:
  - trusty

