language: 
  - node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

notifications:
  email:
    - false

sudo:
  - required

before_install:
  - sudo add-apt-repository -y ppa:wine/wine-builds && sudo apt-get update && sudo apt-get install -y --install-recommends winehq-devel
  - sudo winetricks -q tahoma liberation ie8 gecko dotnet20 msi2 fontfix mono22 allfonts

install:
  - npm install --unsafe-perm=true --allow-root
  - npm run rebuild

script:
  - gulp js
  - npm run build

os: 
  - linux

dist:
  - trusty

