language: 
  - node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

notifications:
  email:
    - false

sudo:
  - required

install:
  - sudo npm install
  - sudo npm run rebuild

script:
  - npm run start
  - gulp

os: 
  - linux

dist:
  - trusty

