language: node_js
node_js:
  - "iojs"
cache:
  npm:
    - true

notifications:
  email:
    - false

sudo:
  - required

install:
  - sudo npm install --unsafe-perm=true --allow-root
  - sudo npm run rebuild

script:
  - npm run start
  - gulp

- os: 
  - linux

dist:
  - xenial

